### ISSUE TITLE
Bug in "Skjemaoversikt" when using markdown

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#246]
Sometimes I have noticed a bug when moving the fields up/down in the "Skjemaoversikt". When rearranging the order, the content gets copied to the other item. I have done some testing and it seems to only happen when markdown is activated. It also happens on other types than Beskjed.

To reproduce:
1. Create new form
2. Create first field, "Beskjed", add some text, activate markdown and e.g. make the text bold
3. Create a second field
4. Rearrange the order in Skjemaoversikt
5. Look at the text in Skjemaoverskrift and "Skriv spørsmål", one duplicates the other

Let me know if you cannot reproduce the error, then I can show it to you live or send more printscreens 

![image](https://user-images.githubusercontent.com/77841246/107938906-4f336080-6f86-11eb-95ba-12a3cbd3e621.png)

**Comment by mgunnerud** [comment]
I debugged this; after reordering items, the Markdown editor dispatched an onChange event which caused this. Looks like the Markdown editor is still attached to the first item, even though it should be on the second. I this this is because React is confused when re-rendering <Question> components, since the key is index (which can have some weird side effects such as this). I changed the key when rendering question: 

https://github.com/helsenorge/structor/blob/e7fa3842675d34ef366118edf8ae954cdd3c48ee/src/views/FormBuilder.tsx#L52

to 

`<div key={x.linkId}>`

which seems to fix the problem.
