### ISSUE TITLE
Some elements are not displayed

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#285]
When uploading a form that has been created in excel, some elements are not displayed in the preview.

**To reproduce:**
1. Upload this json into Skjemabyggeren and see that Group 5 (Helsetilstand) has many elements: https://gist.github.com/MariaNHN/4a1e7d70b7be00aa4fafdb79cfff6b73 

2. Then preview the form, and no elements displayed under "Helsetilstand"

![image](https://user-images.githubusercontent.com/77841246/110937560-d29c6380-8332-11eb-9a19-56687ecc23dc.png)

**Comment by GeirLoken** [comment]
@MariaNHN This happens because the questionnaire from Excel is FHIR v3, while Skjemabyggeren requires FHIR v4.

Some differences between v3 and v4 (related to this issue) are:
- `"options": {"reference": "#1102"},` should be replaced with `"answerValueSet": "#1102",`
- `enableWhen` must contain `operator` in v4

**Comment by losolio** [comment]
I think this could be solved by regenerating r4 json file using fhir-tools, and upload a valid r4 questionnaire definition. Closing this, but feel free to reopen if not true!
