### ISSUE TITLE
Error msg. "Ikke definert tittel"

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#320]
Sometimes the text "Ikke definert tittel" shows up in the drop down for enable when. 

Helse Vest has seen this error many times (they have used other elements, so this is not related to mottaker liste only). I have so far only found it in this form: https://gist.github.com/MariaNHN/7e0cbc508df2b3cec81d58e763a1642f

 
![image](https://user-images.githubusercontent.com/77841246/112989502-488f3000-9165-11eb-9ed5-c496d54d663b.png)

**Comment by mgunnerud** [comment]
In this case, it is because the item does not have the "text" property. However, it has the following markdown: "Velg det sykehuset som du tenker å oppsøke. Skjemaet vil bli lagret i journalen din hos det sykehuset du velger." We can change the dropdown to use markdown if the item does not have a "text" attribute. (why does this element use markdown though? There is is no markdown formatting in the sentence above)

However, this will not solve the issue of items without "text" and "_text" (markdown extension). This can happen for for example groups without a header. I guess this is a question about design; if we hide them, the dropdown might look confusing since it is missing a level. I prefer showing the item, but perhaps the "Ikke definert tittel" text can be changed to something else.
