### ISSUE TITLE
Age check and EW

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#369]
Some elements should only be visible if the user is 13 years or older. 

To reproduce:
1. Create new form. Add a Kortsvar element and add egendefinert beriking: Patient.extension.where(url = 'http://helsenorge.no/fhir/StructureDefinition/sdf-age').value
2. Add a Beskjed and in Betinget visning set to 13 or more

See printscreens below and test here: https://tjenester-hn-mas-02.int-hn.nhn.no/skjemautfyller-v2/Aldertest 
The Beskjed is visible for users under 13.    

Beriking:
![image](https://user-images.githubusercontent.com/77841246/119807743-bf397700-bee3-11eb-99c8-a0d146dbf143.png)

Enable when: 
![image](https://user-images.githubusercontent.com/77841246/119807871-daa48200-bee3-11eb-882c-a06f6f358d17.png)

The result:
![image](https://user-images.githubusercontent.com/77841246/119808144-222b0e00-bee4-11eb-8dce-8b05aba87b99.png)

**Comment by mgunnerud** [comment]
@MariaNHN I think beriking can only set text values; so it is not possible to compare numbers or dates for fields with beriking in the form filler. The comparison here will be "3" >= "13" which is true since the text "3" is after the text "1" in programmatic sorting. To make this enableWhen work with the current form filler implementation, there must be 13 enableWhens to check for
answer.exists AND answer not equal to 0 AND answer not equal to 1 AND answer not equal to 2 AND ... AND answer not equal to 12.

**Comment by MariaNHN** [comment]
Aha, thanks! 
That seems to work: https://tjenester-hn-mas-02.int-hn.nhn.no/skjemautfyller-v2/Aldertest?pnr=11129504694 

Just curious: why do we need to check for exists when the field is beriket?

**Comment by mgunnerud** [comment]
I suggested to check for exists in case the field value is not set (in the case the user is not logged in, not sure if this will be the case for this form)
